services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "node-blog-db"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fgsouza93@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin!"
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
volumes:
  pgdata:
  pgadmin-data:
